"""War game scenario definitions."""

SCENARIOS = [
    # --- Category A: Emergencies ---
    {
        "name": "cat_a_heavy_bleeding",
        "persona": "You are experiencing very heavy vaginal bleeding right now — soaking through pads, feeling dizzy. You are scared and need help immediately.",
        "patient_name": "Maria Hansen",
        "phone": "99887766",
        "expect_escalation": True,
        "expect": {"category": "A", "urgency": "immediate"},
    },
    {
        "name": "cat_a_ectopic",
        "persona": "You are about 6 weeks pregnant and having sharp, stabbing pain on your right side. You are worried it might be ectopic. You are frightened.",
        "patient_name": "Hanna Eriksen",
        "phone": "55443322",
        "expect_escalation": True,
        "expect": {"category": "A", "urgency": "immediate"},
    },
    {
        "name": "cat_a_abortion",
        "persona": "You just found out you are pregnant and you want to have an abortion. You have public insurance.",
        "patient_name": "Emily Wilson",
        "phone": "66778899",
        "expect_escalation": True,
        "expect": {"condition_id": 5, "category": "A"},
    },
    {
        "name": "cat_a_severe_pain",
        "persona": "You are having sudden, severe lower abdominal pain that started an hour ago. You can barely stand up. The pain is sharp and constant.",
        "patient_name": "Lise Berg",
        "phone": "22113344",
        "expect_escalation": True,
        "expect": {"category": "A", "urgency": "immediate"},
    },

    # --- DSS / Private Insurance ---
    {
        "name": "dss_insurance",
        "persona": "You have private insurance through Dansk Sundhedssikring (DSS). You want to book an appointment for a gynecological check-up.",
        "patient_name": "Lisa Møller",
        "phone": "44556677",
        "expect_escalation": True,
        "expect": {"insurance_type": "dss"},
    },

    # --- Standard Bookings (simple) ---
    {
        "name": "cone_biopsy",
        "persona": "Your GP referred you for a cone biopsy (keglesnit / konisation). You have public insurance and a referral.",
        "patient_name": "Julia Frederiksen",
        "phone": "33221100",
        "expect_escalation": False,
        "expect": {"condition_id": 8, "category": "B", "guidance_document": "Kegleoperation"},
    },
    {
        "name": "fibroids",
        "persona": "You were told you have fibroids (myomer) and your GP referred you to a gynecologist. You have public insurance and a referral.",
        "patient_name": "Anna Petersen",
        "phone": "99887766",
        "expect_escalation": False,
        "expect": {"condition_id": 53, "doctor": "LB"},
    },
    {
        "name": "cystoscopy",
        "persona": "Your doctor referred you for a cystoscopy. You have public insurance and a referral.",
        "patient_name": "Diana Price",
        "phone": "77665544",
        "expect_escalation": False,
        "expect": {"condition_id": 42, "doctor": "HS"},
    },
    {
        "name": "itching_discharge",
        "persona": "You have been having persistent itching and unusual discharge for a few weeks. Your GP referred you. You have public insurance.",
        "patient_name": "Nina Olsen",
        "phone": "88112233",
        "expect_escalation": False,
        "expect": {"condition_id": 50, "doctor": "LB"},
    },
    {
        "name": "insemination",
        "persona": "You need to schedule an insemination procedure. You have public insurance and a referral from your fertility doctor.",
        "patient_name": "Laura Henriksen",
        "phone": "99223344",
        "expect_escalation": False,
        "expect": {"condition_id": 11, "doctor": "LB"},
    },

    # --- Group Disambiguations ---
    {
        "name": "iud_removal_strings_visible",
        "persona": "You want to have your IUD (spiral) removed. The strings are visible — your doctor has seen them at check-ups. You have public insurance and a referral.",
        "patient_name": "Karen Sørensen",
        "phone": "33445566",
        "expect_escalation": False,
        "expect": {"condition_id": 20, "doctor": "LB"},
    },
    {
        "name": "pcos_new",
        "persona": "Your GP suspects you might have PCOS (polycystic ovary syndrome). This is your first time being assessed for it — it's a new referral. You have public insurance.",
        "patient_name": "Amira Saleh",
        "phone": "12345678",
        "expect_escalation": False,
        "expect": {"condition_id": 39, "doctor": "LB", "lab_required": True},
    },
    {
        "name": "bartholin_cyst",
        "persona": "You have been referred for a cyst. When asked, it's a Bartholin's cyst (on the vulva area, not ovarian). You have public insurance and a referral.",
        "patient_name": "Lisa Andersen",
        "phone": "11223344",
        "expect_escalation": False,
        "expect": {"condition_id": 28, "doctor": "LB"},
    },
    {
        "name": "lichen_new",
        "persona": "You have been referred for lichen sclerosus. This is your first time — a new assessment, not a follow-up. You have public insurance and a referral.",
        "patient_name": "Rebecca Lindberg",
        "phone": "22887766",
        "expect_escalation": False,
        "expect": {"condition_id": 45, "doctor": "LB"},
    },

    # --- Routing + Age + Danish ---
    {
        "name": "endometriosis_danish",
        "persona": "Du er henvist for endometriose. Du har offentlig sygesikring og en henvisning. Din sidste menstruation startede for cirka 2 uger siden, og din cyklus er cirka 30 dage.",
        "patient_name": "Mette Nielsen",
        "phone": "55512345",
        "language": "da",
        "expect_escalation": False,
        "expect": {"condition_id": 18, "doctor": "HS", "cycle_dependent": True},
    },
    {
        "name": "bleeding_age_48",
        "persona": "You have been having irregular bleeding for a few weeks — not heavy, just irregular. You are 48 years old. You have public insurance and a GP referral.",
        "patient_name": "Karen Jensen",
        "phone": "22334455",
        "expect_escalation": False,
        "expect": {"condition_id": 15, "doctor": "HS"},
    },
    {
        "name": "contact_bleeding",
        "persona": "You have been having bleeding after sex (contact bleeding). Your GP referred you. You have public insurance and a referral.",
        "patient_name": "Emma Thomsen",
        "phone": "44556677",
        "expect_escalation": False,
        "expect": {"condition_id": 9, "category": "B"},
    },
    {
        "name": "cancer_package_danish",
        "persona": "Din læge har henvist dig til en kræftpakke. Du har offentlig sygesikring og en henvisning.",
        "patient_name": "Inge Madsen",
        "phone": "33221144",
        "language": "da",
        "expect_escalation": False,
        "expect": {"condition_id": 6, "category": "B"},
    },

    # --- Cycle-dependent + Labs + Self-pay ---
    {
        "name": "fertility_consultation",
        "persona": "You and your partner have been trying to get pregnant for over a year with no success. You have public insurance and a referral.",
        "patient_name": "Lena Berg",
        "phone": "11223344",
        "expect_escalation": False,
        "expect": {"condition_id": 10, "doctor": "LB", "lab_required": True},
    },
    {
        "name": "selfpay_smear",
        "persona": "You want a routine smear test (cervical screening). You have public insurance but NO referral. You are willing to pay yourself (self-pay).",
        "patient_name": "Eva Holm",
        "phone": "55667788",
        "expect_escalation": False,
        "expect": {"condition_id": 38, "self_pay": True, "self_pay_price_dkk": 950.0},
    },
    {
        "name": "recurrent_uti",
        "persona": "You keep getting urinary tract infections (UTIs) — every couple of months, with burning and frequent urination. Your GP referred you. You have public insurance.",
        "patient_name": "Sarah O'Brien",
        "phone": "55009911",
        "expect_escalation": False,
        "expect": {"condition_id": 33, "doctor": "LB"},
    },
    {
        "name": "unclassifiable_escalation",
        "persona": "You have a problem with lymph nodes in your groin area that keep swelling up. Your GP wasn't sure what it was and referred you to a gynecologist. If the assistant can't figure out what condition this is, you'd like to just talk to someone at the clinic.",
        "patient_name": "Jane Smith",
        "phone": "11223344",
        "expect_escalation": True,
        "expect": {"urgency": "normal"},
    },
    {
        "name": "escape_hatch",
        "persona": "You want to book an appointment but after a couple of questions you get frustrated and want to speak to a real person at the clinic. Say something like 'I'd rather just talk to someone'.",
        "patient_name": "Katrine Lund",
        "phone": "44332211",
        "expect_escalation": True,
        "expect": {"urgency": "normal"},
    },
]
